### ISSUE TITLE
Modify the options under the section "Final Diagnosis and Plan" to be the exact duplicate of the options under the updated section "Pathology Description" with just the addition of "Provider Name" and "Phone #"

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/smartcerv#102]
* Normal
* Benign
* CIN 1/HPV
* CIN 2
* CIN 3
* Adenocarcinoma-in-situ
* Malignant
  * Microinvasive cancer
  * Squamous
  * Adenocarcinoma
  * Adenosquamous
* Insufficient for processing

**Comment by Mellorison** [comment]
Modified the options under the section "Final Diagnosis and Plan" to be the exact duplicate of the options under the updated section "Pathology Description" with just the addition of "Provider Name" and "Phone #"
