### ISSUE TITLE
Frequency and Duration fields must not be active if a drug checkbox is not checked

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/smartcerv#103]
![Screenshot_2019-06-10-20-57-24-078 1](https://user-images.githubusercontent.com/25362528/59219434-c9f98500-8bc2-11e9-8448-6bdd8a8e3da6.jpeg)

**Comment by kaykabwe** [comment]
Resolved. Waiting on next merge to develop branch
