### ISSUE TITLE
When "No" is selected under EDI, the load and take image button must disappear or be disabled

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/smartcerv#111]
![Screenshot_2019-06-20-11-08-12-549](https://user-images.githubusercontent.com/25362528/59837581-c1851500-934d-11e9-9ab2-b39e035b10b4.jpeg)

**Comment by AndreLesa** [comment]
Estimate - Release V1.0.0-alpha.3

**Comment by tobiasmakai** [comment]
Duplicate of #181 https://github.com/BlueCodeSystems/smartcerv/issues/181
