### ISSUE TITLE
Change all drug sections to align to the prescriptions in VIA 

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/smartcerv#112]
Replace the drug section, add the checklist in VIA prescription form and make it collapsable (see family planning checklist)
![LEEP prescriptions](https://user-images.githubusercontent.com/25362528/59847004-ab814f80-9361-11e9-8509-e1e20e7c998c.jpeg)
![VIA prescriptions](https://user-images.githubusercontent.com/25362528/59846981-9d333380-9361-11e9-94e0-39f3743d16a3.jpeg)

**Comment by AndreLesa** [comment]
Estimate - Release V1.0.0-alpha.3

**Comment by Mellorison** [comment]
Changed all drug sections to align to the prescriptions in VIA .
