### ISSUE TITLE
Text should be "Reason for no EDI" or just "Reason"

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/smartcerv#139]
![Screenshot_2019-07-21-23-52-22-479 1](https://user-images.githubusercontent.com/25362528/61597609-e4d40600-ac12-11e9-8a3e-caa4c5c2cf16.jpeg)

**Comment by Wanji-Allan** [comment]
![Screenshot_2019-07-29-11-59-16-154](https://user-images.githubusercontent.com/50628380/62040379-cf09a680-b1f9-11e9-8c5a-cbfdffc20783.jpeg)
Text field still showing incorrect wording.
