### ISSUE TITLE
Reproductive Health History form can be submitted without entering the Parity Number in the required field

### ISSUE THREAD

**Issue by Wanji-Allan** [BlueCodeSystems/smartcerv#147]
Form needs to NOT be able to be submitted without the Parity Number.
![Screenshot_2019-07-24-15-16-11-661](https://user-images.githubusercontent.com/50628380/61796748-559f3c00-ae26-11e9-852c-6b9be722f65b.jpeg)

**Comment by AndreLesa** [comment]
Related to issue #150
