### ISSUE TITLE
Text field for client's phone number should not accept alphabetical values

### ISSUE THREAD

**Issue by Wanji-Allan** [BlueCodeSystems/smartcerv#148]
The text field must only allow for numerical values and/or relevant symbols to be entered.
![Screenshot_2019-07-24-15-44-52-659](https://user-images.githubusercontent.com/50628380/61798948-7ff2f880-ae2a-11e9-9cfe-60b58aba579d.jpeg)

**Comment by tobiasmakai** [comment]
Make phone # field behave like parity field when activated i.e. keypad should switch to numbers mode
