### ISSUE TITLE
Text field to enter the date of Last known HIV-negative test result is not retaining the data entered after form is submitted. 

### ISSUE THREAD

**Issue by Wanji-Allan** [BlueCodeSystems/smartcerv#151]
![Screenshot_2019-07-25-15-38-01-131](https://user-images.githubusercontent.com/50628380/61879041-7e8d0300-aef2-11e9-8a2e-28ea97ddc7ce.jpeg)

**Comment by AndreLesa** [comment]
Covered by issue #146
