### ISSUE TITLE
Unable to upload more than one image under EDI. 

### ISSUE THREAD

**Issue by Wanji-Allan** [BlueCodeSystems/smartcerv#152]
The image selected is replaced when you attempt to upload another from the Gallery.

**Comment by Mellorison** [comment]
The maximum number of uploads under the EDI Insights gallery is Two. During a visit session; Select a photo then submit. Repeat this step during said visit session to add the second photo to the EDI gallery; then End the visit session. Click the EDI image button on the Patient dashboard to transfer you to the EDI Insights gallery. You should see two photos displayed.

**Comment by tobiasmakai** [comment]
@Wanji-Allan close this issue if all is well
