### ISSUE TITLE
Change the spelling of 'Perineuem' on the Physical Exam form to 'Perineum'

### ISSUE THREAD

**Issue by Wanji-Allan** [BlueCodeSystems/smartcerv#156]

**Comment by csamiselo** [comment]
kindly attach screen shot

**Comment by Wanji-Allan** [comment]
![Screenshot_2019-07-29-12-02-11-847](https://user-images.githubusercontent.com/50628380/62039834-b8168480-b1f8-11e9-96bf-9673e282d9ec.jpeg)
