### ISSUE TITLE
Client Registration form should not allow Date of Birth entry to be further than the present date. 

### ISSUE THREAD

**Issue by Wanji-Allan** [BlueCodeSystems/smartcerv#158]
![Screenshot_2019-07-30-15-23-09-079](https://user-images.githubusercontent.com/50628380/62134598-11f27980-b2e1-11e9-9149-e3e962ef9968.jpeg)

**Comment by tobiasmakai** [comment]
Further, extend this to enrolment into the cervical cancer service. Application should prevent any client below the age of 10 from getting enrolled into cervical cancer service. Separate issue will be opened but it's you look into it as you work on the issue
