### ISSUE TITLE
Make some changes to the prescriptions form

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/smartcerv#198]
- [x] Change dosage from "125-250 mg" to "500 mg - 1g" on "Ceftriaxone" 
- [x] Change dosage from "400mg" to "250/500mg" on "Cefixime"
- [x] Change dosage from "400-500mg" to "250 - 500mg" on "Erythromycin"
- [x] Add "Acyclovir 400mg" to the list of drugs 
- [x] Add "QID" to the drop down list of the frequency
![Screenshot_2019-08-14-17-56-31-891](https://user-images.githubusercontent.com/25362528/63036199-dea51280-bebc-11e9-92fa-24a68d52fb96.jpeg)

**Comment by kaykabwe** [comment]
Added to test server
