### ISSUE TITLE
The "Enroll Patient" icon should lead to a list of clients that have not yet been enrolled

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/smartcerv#264]
List should be pre-filtered and NOT list the already enrolled clients. This filter should only apply when user takes the route  Enroll Patient >>> Records
![Screenshot_2019-10-07-21-07-12-413 1](https://user-images.githubusercontent.com/25362528/66341425-8aac2c80-e947-11e9-97d1-1569e464f9e4.jpeg)
![Screenshot_2019-10-07-21-07-36-247 1](https://user-images.githubusercontent.com/25362528/66341476-ad3e4580-e947-11e9-95fd-f604302f472d.jpeg)

**Comment by Davidju97** [comment]
**How to test**

1. From the home page navigate to cervical cancer page
2. From Cervical cancer page navigate to Enroll Client
3. In the Cervical cancer register click add icon and register a new client
4.Once new patient has been created ,click on the newly registered client and client dashboard will open
5. on client dashboard navigate to client enrollment and enroll the client
**Expected Result**
When the new client or any existing client is enrolled into the cervical cancer service they should automatically be removed from the  cervical cancer enroll client register but visible in the cervical cancer register.
