### ISSUE TITLE
If a date field is filled in by mistake when it is supposed to be left blank there is no way of clearing the field even before submitting the form

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/smartcerv#278]

**Comment by Wanji-Allan** [comment]
@tobiasmakai 
 A little more clarification needed on this.

**Comment by tobiasmakai** [comment]
@Wanji-Allan test date fields under "Previous Cervical Cancer Screening and Treatment" on the Reproductive Health History form to verify this.
Enter a date and clear the field
