### ISSUE TITLE
Implement an exit prompt dialog modal when back navigation is pressed during a visit session

### ISSUE THREAD

**Issue by hallix** [BlueCodeSystems/smartcerv#283]

**Comment by tobiasmakai** [comment]
This dialog should not pop up is the action is "Abort Visit" because the user is just from receiving another dialog asking whether they are sure they want to abort or not.

**Comment by tobiasmakai** [comment]
When in Edit mode, the back navigation is prompting the abort prompt and when Yes is chosen it is deleting the visit. I think that should not be then case, it will potentially confuse users.

**Comment by tobiasmakai** [comment]
Dialog toggled between abort visit and end visit a couple of times yet only the back button was being tapped. No longer able to recreate the experience but feature can be rechecked just to make sure. Closing the issue.
