### ISSUE TITLE
Add an abort visit action during a visit session

### ISSUE THREAD

**Issue by hallix** [BlueCodeSystems/smartcerv#290]

**Comment by Davidju97** [comment]
**HOW TO TEST**
The Aborting of a visit  test is performed in two phases, phase one is performed in smartcerv application and phase two is performed in Openmrs. 
The steps below  fall under phase one and are performed in the smartcerv app
1.Navigate ->home page->Cervical cancer page->Client register
2.On the cervical cancer client register click on clients's name to open the patients' dashboard
3.On the patient's dashboard you can either click the add (+) icon and select VIA on the pop up dialog to start a new visit or click edit to open an already existing visit.
4.On the visit page page click the Abort visit button. Please note that the Abort visit button is not clickable till a visit has been started.
5.Once the Abort visit has been clicked a dialog is displayed, click no to cancel or click yes to proceed with the abortion.
**EXPECTED RESULTS**
If its a new visit that has been aborted it will not be displayed on the patients dashboard and if it was an already existing the aborted visit will not be displayed on the patients dashboard.

The steps below are under phase 2 therefore are to be performed in Openmrs
1.Log in into Openmrs
2.Navigate to system administration->Advanced administration->find/create patient
3.In the search bar type in the clients name whose visit was aborted and click on their name when it appears in the search results.
4.The patients dashboard will open  and navigate to visits
**EXPECTED RESULTS** 
The visit that was aborted is not displayed on the visits page..
**PLEASE NOTE THAT A VISIT THAT HAS ALREADY BEEN SYNCED AND UPLOADED TO OPENMRS WILL STILL BE VISIBLE  UNDER OPENMRS PATIENT DASHBOARD  VISITS **

**Comment by tobiasmakai** [comment]
1. What is the essence if keeping the aborted visit in OMRS?
2. Can the Abort Visit feature be said to be the same as delete visit function?
3. Why should the insights page still return information from the aborted visit?
![Screenshot_2020-01-16-16-09-00-136 1](https://user-images.githubusercontent.com/25362528/72531704-b8740c00-387a-11ea-8669-0f6e1249309f.jpeg)

**Comment by tobiasmakai** [comment]
Aborting visit in edit mode is the same as deleting the visit. Under rare circumstances will a provider intend to delete the visit in **edit mode**. Let us find a better solution on how the abort can be handled better if in edit mode.

**Comment by tobiasmakai** [comment]
Looks like it working fine now but dialog still alternated a couple of times from End to Abort visit  when back button was tapped. Closing the issue.
