### ISSUE TITLE
Grammatical error. Should read 'Delayed Cryotherapy' on Visit Page. 

### ISSUE THREAD

**Issue by Wanji-Allan** [BlueCodeSystems/smartcerv#312]
![Screenshot_2019-11-18-12-54-51-472](https://user-images.githubusercontent.com/50628380/69047104-18793e00-0a03-11ea-8f93-5ae4056186ff.jpeg)

**Comment by tobiasmakai** [comment]
Looks correct to me...

**Comment by tobiasmakai** [comment]
Oh I see the PHY

**Comment by tobiasmakai** [comment]
Not done
![Screenshot_2020-01-16-15-17-30-624 1](https://user-images.githubusercontent.com/25362528/72528534-edc92b80-3873-11ea-9f2b-6fcee2d278a5.jpeg)
