### ISSUE TITLE
Implement Edit feature for Client ID

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/smartcerv#318]

**Comment by Davidju97** [comment]
**HOW TO TEST**
1.Navigate from home page->cervical cancer->client register
2.On cervical cancer client register page click on client's name to open the patient's dashboard
3. On the patient's dashboard you will notice two icons on the  top right of the screen ,one icon being the sync (clouds) and the other being the menu (three vertical dots). Click on the menu icon.
4.Once the menu icon is clicked a menu will open. the menu has two options edit and delete, click on edit.
5.when edit option is clicked the Edit clients demographics page will open. Edit the text next to Client ID and click the submit button at the bottom of the page
**EXPECTED RESULTS**
The newly submitted client id is displayed on the patients'dashboard.

**Comment by tobiasmakai** [comment]
Client ID gets successfully edited on client side quite alright but does not update in OMRS after sync, how long should it take for the changes to be effected afte sync complete?
![Screenshot_2020-01-16-09-11-22-885 1](https://user-images.githubusercontent.com/25362528/72502067-24398300-3841-11ea-91db-d1c71b523482.jpeg)
![image](https://user-images.githubusercontent.com/25362528/72502079-2b609100-3841-11ea-9f2f-4651350d2ef0.png)

**Comment by tobiasmakai** [comment]
This applies to editing demographics too

**Comment by tobiasmakai** [comment]
Edits still not getting effected in OMRS
