### ISSUE TITLE
Add delete feature for Client's full record 

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/smartcerv#319]
Record must be archived

**Comment by Davidju97** [comment]
**HOW TO TEST**
1.Navigate from home page to either Records(OPD )register or cervical cancer register
2.In the register click on the patient's name to open the patient's dashboard
3. On the top right of the patient's dashboard you will notice two icons, one being the sync (clouds) icon and the other being the menu (three vertical dots) icon. click on the menu icon.
4.When menu icon is clicked menu will open.menu has two items edit and delete click on delete.
5.When delete is clicked a dialog will be displayed prompting the user to confirm deletion. click no to cancel or click yes to proceed with the deletion.
**EXPECTED RESULTS**
deleted client does not appear in the register.

**PLEASE NOTE THAT A CLIENT DELETED FROM THE CERVICAL CANCER REGISTER WILL STILL BE VISIBLE IN THE RECORDS(OPD) REGISTER AS THEY HAVE ONLY BEEN REMOVED FROM THE CERVICAL CANCER  SERVICE.TO COMPLETELY DELETE THE CLIENT,DELETE FROM THE RECORDS(OPD) REGISTER **

**Comment by tobiasmakai** [comment]
Deletion not getting effected in omrs

**Comment by tobiasmakai** [comment]
Deletion still not getting effected in omrs
