### ISSUE TITLE
Implement camera feature 

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/smartcerv#34]
**Current Business Process**
During the screening process (after/during physical exam and/or VIA testing); 
1. Provider captures the client's cervix using an HD camera 
2. Provider examines the image on the camera screen for any details that may have been missed when using naked eye 
3. At the end of the whole screening service, provider transfers all images taken that day from the camera memory into the computer
4. Provider resizes the images using a software called resize genius 
5. Provide renames each image after the Client IDs according to the order of the forms for the clients seen that day
6. Client goes into the access database and begins to upload each picture tying it to a client's record 

**Task:** Implement this process in SmartCerv to enable provider access to the images from the client's dashboard (Find ways of having this image seamlessly transferred to the tablet from the camera and having it tied to the right client)

**Comment by tobiasmakai** [comment]
[Photo list.PDF](https://github.com/BlueCodeSystems/smartcerv/files/3054969/Photo.list.PDF)
How they index the images currently

**Comment by AndreLesa** [comment]
@tobiasmakai give some feedback on in-facility experience with the cameras

1. Types of cameras encountered.
2. Ease of setup.
3. Are people actually using the feature.

**Comment by tobiasmakai** [comment]
People are not using the feature because it is not useful with the version of Canon cameras currently in the facilities. So far I have not encountered a facility that is using PowerShoot SX70  most of them are using SX60 with a few still using SX40
