### ISSUE TITLE
First letter of the text field should be Capital letter by default (see ZEIR forms)

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/smartcerv#61]
![Screenshot_2019-05-10-05-13-23-118 1](https://user-images.githubusercontent.com/25362528/57516440-03fe0f80-7315-11e9-96f9-c9b48600098e.jpeg)

**Comment by csamiselo** [comment]
@hallix @tobiasmakai , kindly requesting permission to close this issue.

**Comment by tobiasmakai** [comment]
In the latest build, first letter will only get capitalized when user hits the space key. Is that final?

**Comment by csamiselo** [comment]
Capitalization method used, capitalizes the first letter of the first word in a sentence.

**Comment by tobiasmakai** [comment]
Still not working in alpha 4 
![Screenshot_2019-08-02-22-46-39-340](https://user-images.githubusercontent.com/25362528/62398919-6d8b6400-b57a-11e9-886d-e92508d36050.jpeg)
