### ISSUE TITLE
VIA Screening date field must be pre-filled with today's date

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/smartcerv#62]
![Screenshot_2019-05-10-05-25-40-620 1](https://user-images.githubusercontent.com/25362528/57517280-c8644500-7316-11e9-964a-06c720decf27.jpeg)

**Comment by tobiasmakai** [comment]
Form must not be submittable if the date field is empty

**Comment by hallix** [comment]
This field should be removed

**Comment by tobiasmakai** [comment]
See #248
