### ISSUE TITLE
Selecting 'None' on family planning methods must disable or grey out all the other options

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/smartcerv#66]
![Screenshot_2019-05-10-05-50-23-982 1](https://user-images.githubusercontent.com/25362528/57518739-01ea7f80-731a-11e9-9447-8a48da0638f6.jpeg)

**Comment by csamiselo** [comment]
@hallix @tobiasmakai , kindly requesting permission to close this issue.
