### ISSUE TITLE
Prescriptions: Add  'PRN' and 'STAT' to the frequency options 

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/smartcerv#73]
![Screenshot_2019-05-10-06-30-10-691 1](https://user-images.githubusercontent.com/25362528/57521116-b0dd8a00-731f-11e9-8aee-00cad6278ce8.jpeg)

**Comment by kaykabwe** [comment]
@tobiasmakai PRN and STAT values added
