### ISSUE TITLE
Reorder the radiobuttons and the Image load and Take photo buttons to have the Yes and No radiobuttons come before the image buttons

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/smartcerv#78]
The image buttons can only be active (selectable) if the Yes option is selected
![Screenshot_2019-05-14-03-04-51-661 1](https://user-images.githubusercontent.com/25362528/57677717-c3a9d480-7627-11e9-9c48-0e2328103c2d.jpeg)

**Comment by Mellorison** [comment]
Rearrangement of Radio Buttons was already done. Awaiting Validation by @csamiselo

**Comment by Mellorison** [comment]
Resolved.

**Comment by csamiselo** [comment]
Seen
