### ISSUE TITLE
HIV Status Unknown: correct the spelling for referred

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/smartcerv#79]
![Screenshot_2019-05-14-09-05-20-182 1](https://user-images.githubusercontent.com/25362528/57705243-c62a1f80-7663-11e9-9f83-bc2ca37d7712.jpeg)

**Comment by csamiselo** [comment]
@hallix @tobiasmakai , kindly requesting permission to close this issue.

**Comment by tobiasmakai** [comment]
I can no longer see this field in the latest build, was the decision to completely remove it?
![Screenshot_2019-06-12-16-58-23-189 1](https://user-images.githubusercontent.com/25362528/59362313-88d4b280-8d33-11e9-8d56-b043936ddec8.jpeg)
