### ISSUE TITLE
Make the following modifications to the Reason For Referral Form;

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/smartcerv#91]
- [x] Change; “< 75% of cervix” to “> 75% of cervix”
- [x] Change; “Lesion extends into os” to “Lesion extends into endocervix”
- [x] Remove option: “Lesion too thick for cryo”
- [x] Remove option; “Atypical vessel”
- [x] Remove option; "Mosaicism/Punctation"
- [x] Remove option; "Extends into cervical os” as it is a duplicate of the one above
- [x] Change; “Post cryo lesion” to “Post-treatment lesion”
- [x] Remove; "Reason for other" but add a field to enter the "Other" option in question to be triggered by the selection of the "Yes" radiobutton under the option "Other"
**Note:** The next form "LEEP Evaluation" should be a duplicate of this form maybe with the exception of the image brought forth from the referring facility but give evaluating provider an option to load image in case they take an image during the LEEP evaluation.
![Screenshot_2019-06-10-18-17-03-828 1](https://user-images.githubusercontent.com/25362528/59210775-a75d7100-8bae-11e9-9834-cb4a3c5cbf7d.jpeg)

**Comment by Mellorison** [comment]
Made requested modifications to the Reason For Referral Form
