### ISSUE TITLE
Change title label of form from “Treatment/Results/Pathology” to “OUTCOMES”

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/smartcerv#92]
![Screenshot_2019-06-10-18-44-35-925 1](https://user-images.githubusercontent.com/25362528/59211297-d1fbf980-8baf-11e9-9d6f-1a530a3399ae.jpeg)

**Comment by Mellorison** [comment]
Changed title label of form from “Treatment/Results/Pathology” to “OUTCOMES”
