### ISSUE TITLE
Change subtitle label from “Treatment/Results/Pathology” to “Procedures” and change the listings under as follows;

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/smartcerv#93]
- [x] Remove the label "Treatment"
- [x] Change "LEEP" to "LEEP/LLETZ"
- [x] Add "Thermal Coagulation" to the list of procedures 
- [x] Change "Cautery of transformation zone" to "Cautery"
- [x] Change "No treatment needed" to "No procedures needed"
- [x] Re-order the options as follows;
      - LEEP/LLETZ
      - Thermal Coagulation
      - Cryotherapy
      - Cautery
      - Biopsy
      - Reffered 
      - No procedures needed
      - Other
- [x] Remove "Reason for other"
- [x] Add text field next to "Other" that only becomes active when the raddiobutton "Other" is selected 
![Screenshot_2019-06-10-19-07-27-285 1](https://user-images.githubusercontent.com/25362528/59212568-150b9c00-8bb3-11e9-927c-182ae5201085.jpeg)

**Comment by Mellorison** [comment]
Resolved.
