### ISSUE TITLE
Make modifications to the "Intraoperative Complications" section as follows;

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/smartcerv#94]
- [x] Change "cervical_arterial_bleed" to "Cervical bleeding" - drop the word arterial
- [x] Change "vaginal_laceration" to "Vaginal laceration"
- [x] Change "anesthesia_reaction" to "Anesthesia reaction"
- [x] Remove "Reason For Other"
- [x] Add a textfield that only becomes active when "Yes" is selected for entering the "other" in question
![Screenshot_2019-06-10-19-23-51-192 1](https://user-images.githubusercontent.com/25362528/59213503-4e450b80-8bb5-11e9-9623-e7481989e1bd.jpeg)

**Comment by Mellorison** [comment]
Resolved.
