### ISSUE TITLE
Add "Hysterectomy" to the options under "Intra-op Interventions" with "Yes and No" radio buttons

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/smartcerv#96]
Can be between "Suturing" and "Self resolved/no intervention needed"
**Also** correct the spelling  for the the word "Intervention" in the label "Self resolved/no intervention needed"
![Screenshot_2019-06-10-19-39-47-378 1](https://user-images.githubusercontent.com/25362528/59214557-949b6a00-8bb7-11e9-881d-e877d9681d7e.jpeg)

**Comment by Mellorison** [comment]
Added "Hysterectomy" to the options under "Intra-op Interventions" with "Yes and No" radio buttons
