### ISSUE TITLE
Change the section label "Results" to "Specimen Dimensions" on the "Final Diagnosis & Plan" form

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/smartcerv#98]
![Screenshot_2019-06-10-20-00-05-359 1](https://user-images.githubusercontent.com/25362528/59215786-6c613a80-8bba-11e9-8b89-35743e639057.jpeg)

**Comment by Mellorison** [comment]
Changed the section label "Results" to "Specimen Dimensions" on the LEEP "Final Diagnosis & Plan" form
