### ISSUE TITLE
Add Section/Field between "Results (to be 'Specimen Dimensions')" and "Margins" label it "Number of sections taken"

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/smartcerv#99]
Field to only allow absolute numbers
![Screenshot_2019-06-10-20-03-31-490 1](https://user-images.githubusercontent.com/25362528/59216139-4b4d1980-8bbb-11e9-8d4d-253ded62f017.jpeg)

**Comment by Mellorison** [comment]
Added Section/Field between "Results (to be 'Specimen Dimensions')" and "Margins" and labelled it as "Number of sections taken"
